# Generated by Django 6.1 on 2026-08-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0021_remove_task_job_id_task_job_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prayer_name",
                    models.CharField(
                        choices=[
                            ("fajr", "Fajr"),
                            ("zhor", "Zhor"),
                            ("asr", "Asr"),
                            ("magrib", "Magrib"),
                            ("eisha", "Eisha"),
                        ],
                        help_text="Name of the prayer",
                        max_length=20,
                        unique=True,
                        verbose_name="prayer name",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Prayer start time", verbose_name="start time"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="Prayer end time", verbose_name="end time"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prayer Schedule",
                "verbose_name_plural": "Prayer Schedules",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="PersonalTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Task title or description",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed task description (optional)",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date of the task", verbose_name="date"),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Task start time", verbose_name="start time"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="Task end time", verbose_name="end time"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("non_negotiable", "Non-Negotiable"),
                            ("secondary", "Secondary"),
                            ("fun", "Fun Activity"),
                        ],
                        default="secondary",
                        help_text="Task category",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the task is completed",
                        verbose_name="is completed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Personal Task",
                "verbose_name_plural": "Personal Tasks",
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(fields=["date"], name="scheduler_p_date_4111e8_idx"),
                    models.Index(
                        fields=["category"], name="scheduler_p_categor_1d7280_idx"
                    ),
                    models.Index(
                        fields=["date", "category"], name="scheduler_p_date_955f90_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskCompletion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        help_text="Whether the task was marked as completed",
                        verbose_name="is completed",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the completion status was recorded",
                        verbose_name="completed at",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Associated personal task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="scheduler.personaltask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Completion",
                "verbose_name_plural": "Task Completions",
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "-completed_at"],
                        name="scheduler_t_task_id_02f9c1_idx",
                    )
                ],
            },
        ),
    ]
