# Generated by Django 6.1 on 2026-08-22 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0022_prayerschedule_personaltask_taskcompletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcompletion",
            name="performance_rating",
            field=models.CharField(
                blank=True,
                help_text="Performance rating based on subtask completion percentage",
                max_length=50,
                null=True,
                verbose_name="performance rating",
            ),
        ),
        migrations.CreateModel(
            name="PrayerCompletion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prayer_name",
                    models.CharField(
                        choices=[
                            ("fajr", "Fajr"),
                            ("zhor", "Zhor"),
                            ("asr", "Asr"),
                            ("magrib", "Magrib"),
                            ("eisha", "Eisha"),
                        ],
                        help_text="Name of the prayer",
                        max_length=20,
                        verbose_name="prayer name",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date of completion record", verbose_name="date"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the prayer was completed",
                        verbose_name="is completed",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the prayer was completed",
                        null=True,
                        verbose_name="completed at",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prayer Completion",
                "verbose_name_plural": "Prayer Completions",
                "ordering": ["-date", "prayer_name"],
                "indexes": [
                    models.Index(fields=["date"], name="scheduler_p_date_1df04c_idx"),
                    models.Index(
                        fields=["prayer_name", "date"],
                        name="scheduler_p_prayer__f47f1b_idx",
                    ),
                ],
                "unique_together": {("prayer_name", "date")},
            },
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Subtask title", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the subtask is completed",
                        verbose_name="is completed",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of subtask within parent task",
                        verbose_name="order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personal_task",
                    models.ForeignKey(
                        help_text="Parent task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="scheduler.personaltask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-Task",
                "verbose_name_plural": "Sub-Tasks",
                "ordering": ["order"],
                "indexes": [
                    models.Index(
                        fields=["personal_task", "order"],
                        name="scheduler_s_persona_6cc5f5_idx",
                    )
                ],
            },
        ),
    ]
