# Generated by Django 6.1 on 2026-08-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scheduler",
            "0023_taskcompletion_performance_rating_prayercompletion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="prayercompletion",
            name="status",
            field=models.CharField(
                choices=[
                    ("prayed", "Prayed"),
                    ("not_yet", "Not Yet"),
                    ("missed", "Missed"),
                ],
                default="not_yet",
                help_text="Status of prayer completion",
                max_length=20,
                verbose_name="completion status",
            ),
        ),
    ]
