# Generated by Django 6.1 on 2026-08-28 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0024_prayercompletion_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaltask",
            name="is_break",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is an auto-inserted break task",
                verbose_name="is break",
            ),
        ),
        migrations.AddField(
            model_name="personaltask",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent task if this is a break",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breaks",
                to="scheduler.personaltask",
            ),
        ),
    ]
