# Generated by Django 6.1 on 2026-08-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0025_personaltask_is_break_personaltask_parent_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Project title", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Project description and notes",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Project start date", verbose_name="start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Project end date", verbose_name="end date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                        ],
                        default="planned",
                        help_text="Current project status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="scheduler_p_status_26844e_idx"
                    ),
                    models.Index(
                        fields=["-start_date"], name="scheduler_p_start_d_7f7a4b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Task title", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Task description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "duration_hours",
                    models.FloatField(
                        default=1.0,
                        help_text="Duration in hours per work session",
                        verbose_name="duration (hours)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order within project",
                        verbose_name="order",
                    ),
                ),
                (
                    "is_scheduled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this task has been scheduled in the main scheduler",
                        verbose_name="is scheduled",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Parent project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="scheduler.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Task",
                "verbose_name_plural": "Project Tasks",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of week to schedule (0=Monday, 6=Sunday)",
                        verbose_name="day of week",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Task start time", verbose_name="start time"
                    ),
                ),
                (
                    "duration_hours",
                    models.FloatField(
                        default=1.0,
                        help_text="Duration in hours",
                        verbose_name="duration (hours)",
                    ),
                ),
                (
                    "weeks",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many weeks to repeat",
                        verbose_name="weeks",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this schedule is active",
                        verbose_name="is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_task",
                    models.ForeignKey(
                        help_text="Associated project task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="scheduler.projecttask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Schedule",
                "verbose_name_plural": "Project Schedules",
            },
        ),
        migrations.AddIndex(
            model_name="projecttask",
            index=models.Index(
                fields=["project", "order"], name="scheduler_p_project_ff4d85_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectschedule",
            unique_together={("project_task", "day_of_week")},
        ),
    ]
